# Generated by Django 3.1.2 on 2020-10-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rating',
            field=models.CharField(default='-/10', max_length=7),
            preserve_default=False,
        ),
    ]
